### ISSUE TITLE
create CONTRIBUTING.md for us 

### ISSUE THREAD

**Issue by sahiljawale54** [RuntimeThinkers/devcheatsheet#2]
All basic guidelines should be included 

Thanks for your contribution,
Runtime Thinkers

**Comment by Purvesh77** [comment]
Hey @sahiljawale54 I want to work on this task 
Can U assign me ?

**Comment by JayrajSingh65** [comment]
> Hey @sahiljawale54 I want to work on this task 
> Can U assign me ?

-  Hey Purvesh thanks for showing your  interest @sahiljawale54 will soon review this

**Comment by Purvesh77** [comment]
OK  @JayrajSingh65
