### ISSUE TITLE
NEW CHEATSHEET REQUEST - Java

### ISSUE THREAD

**Issue by sahiljawale54** [RuntimeThinkers/devcheatsheet#6]
Hey developers!!!

We request a new cheatsheet  on Java programing language

Thanks for your contribution
Team RuntimeThinkers

**Comment by amitroy-thedev** [comment]
Hey @sahiljawale54 please assign me this project

**Comment by amitroy-thedev** [comment]
Hey @sahiljawale54 assign me this project.

**Comment by amitroy-thedev** [comment]
Okay..If the project merge then will it count as hacktoberfest contribution ?
