### ISSUE TITLE
NEW CHEATSHEET REQUEST ON -Python 

### ISSUE THREAD

**Issue by sahiljawale54** [RuntimeThinkers/devcheatsheet#7]
Hey developers!!!

We request a new cheatsheet on the Python programing language

Thanks for your contribution
Team RuntimeThinkers

**Comment by sahiljawale54** [comment]
We are not assigning this issue to any user

All are free to work on this
If the content is up to mark then we will definitely merge it

**Comment by panditsamik** [comment]
> We are not assigning this issue to any user
> 
> All are free to work on this If the content is up to mark then we will definitely merge it

I want to contribute.Please assign me this issue.
